### ISSUE TITLE
[LFS] Version 1.4.1 needs rvtext, even with enable_encryption on true

### ISSUE THREAD

**Issue by maxlefou** [kfischer-okarin/VXAceScripts#17]
When you encrypt the rvtext files, they actually appear as rvdata2 in the Data folder as expected. 
But for some odd reason, the compiled game completely skips the parts with the translated texts. Even when enable_encryption is set to true.
However, this doesn't occur when the rvtext files are included in the compiled game.

I don't have the tools to extract game.rgss3 to check if the compressed rvtext files are there. But the game doesn't even give any errors. It just skips the parts with the texts. I also tried to put a Data folder in a compiled game and put the compressed rvtext files in it, but nothing changes.

The problem occurs on version 1.4.1 and not on 1.3. It's all I know

**Comment by DerTraveler** [comment]
I will look into it! Thank you for reporting the issue (especially the fact that it only occurs in the newer version will be helpful I guess)

**Comment by kfischer-okarin** [comment]
This one should be solved by 1.4.2
